# Generated by Django 3.0.3 on 2020-07-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatis', '0002_auto_20200714_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('time', models.DateTimeField(null=True)),
                ('messages', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('mikrotik', 'Mikrotik'), ('cisco', 'Cisco')], max_length=255),
        ),
    ]
