# Generated by Django 3.0.3 on 2020-07-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatis', '0003_auto_20200716_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('cisco', 'Cisco'), ('mikrotik', 'Mikrotik')], max_length=255),
        ),
    ]
